feat: added `traits()` and `hasTraits()` functions
asyncapi/parser-js pull request #357
Opened 2021-09-07 16:58 UTC by KhudaDad414

**Description**

- this PR will add the above functions to the `Message` and `Operation` classes.

**Related issue(s)**
Resolves #226

2021-09-07 17:41 UTC, KhudaDad414 commented
This PR is ready for review.

2021-09-07 20:01 UTC, magicmatatjahu reviewed
@KhudaDad414 Thanks for contribution. If PR is ready, you can always request for review:

![image](https://user-images.githubusercontent.com/20404945/132403463-9aa66b32-59e3-41b1-82e7-847fb4bb5d61.png)

About PR, overall good, but I don't see logic for handling situation when someone pass `applyTraits: true` as option to the parser :) I wrote how it can be handled in this comment: https://github.com/asyncapi/parser-js/issues/226#issuecomment-914281717

2021-09-08 07:02 UTC, magicmatatjahu requested changes

2021-09-08 07:02 UTC, magicmatatjahu commented on test/models/message_test.js
>  const { expect } = require('chai');
Last thing. Could you add also test cases with `x-parser-original-traits` in Message and Operation object? :)

2021-09-08 08:36 UTC, KhudaDad414 commented
> @KhudaDad414 Thanks for contribution. If PR is ready, you can always request for review:
> 
@magicmatatjahu I don't have the option to request reviews. I can only re-request if someone has already reviewed the PR. 🤔 
<img width="200" alt="Capture" src="https://user-images.githubusercontent.com/32505158/132475677-097d1428-2623-4760-8a7b-b643748053f0.PNG">

2021-09-08 08:39 UTC, magicmatatjahu commented
@KhudaDad414 It is also good, because then as previously reviewer I see your request again :)

2021-09-08 08:45 UTC, magicmatatjahu approved these changes
LGTM! Thanks for contribution!

2021-09-08 08:46 UTC, merged

2021-09-08 08:48 UTC, magicmatatjahu commented
@all-contributors please add @KhudaDad414 for code, test