feat: validate unparsed AsyncAPI document
asyncapi/parser-js pull request #720
Opened 2023-02-07 16:32 UTC by magicmatatjahu

**Description**

Validate unparsed AsyncAPI document (before `$ref`s resolving).

2023-02-07 16:43 UTC, magicmatatjahu commented
@jonaslagoni Could you check?

2023-02-07 16:51 UTC, jonaslagoni requested changes
I guess I dont understand why we don't change the parsing logic to validate before resolving references, and then again after? This fix looks like an incorrect approach to take 🤔 Or is there some underlying reason?

Related to https://github.com/asyncapi/parser-js/issues/405

2023-02-07 16:51 UTC, jonaslagoni commented on test/ruleset/rules/asyncapi-document-unresolved.spec.ts
> +        message: 'Referencing in this place is not allowed',
Why is this needed? Is it not caught by the spec-schema?

2023-02-07 16:51 UTC, jonaslagoni commented on test/ruleset/rules/asyncapi-document-unresolved.spec.ts
> +        message: 'Referencing in this place is not allowed',
Why is this needed? Is it not caught by the spec-schema?

2023-02-07 16:55 UTC, magicmatatjahu commented
@jonaslagoni 

> I guess I dont understand why we don't change the parsing logic to validate before resolving references, and then again after? This fix looks like an incorrect approach to take 🤔 Or is there some underlying reason?

Spectral resolver (and other json-schema resolvers) doesn't validate the json-schema but only resolve it. Also AJV try to validate the json-schema based on json-schema and that's the problem. After referencing we don't know if `$ref` in given place can be located and/or given ref has valid object (for given location, e.g. message etc.). So we exactly validate two things: unresolved AsyncAPI document with refs and with resolved refs (even that deep). I don't know how to make it in different way. That PR is related to the https://github.com/asyncapi/parser-js/issues/405

2023-02-08 06:31 UTC, jonaslagoni commented
Ahh shit, validation happens through spectral now, yea then you cant do a simple double validation once before refs are resolved and once after...

2023-02-08 09:03 UTC, magicmatatjahu commented
@jonaslagoni 

> Ahh shit, validation happens through spectral now, yea then you can't do a simple double validation once before refs are resolved and once after...

this is what I do 😄

2023-02-08 13:50 UTC, jonaslagoni approved these changes

2023-02-09 12:40 UTC, magicmatatjahu commented
/rtm

2023-02-09 12:41 UTC, merged